// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrRPgYs7mZ2piXxqSqkBf5XgXBnnja7RY',
    appId: '1:751235115727:web:23eafc2d815849fab6e5ba',
    messagingSenderId: '751235115727',
    projectId: 'alertmate-26d10',
    authDomain: 'alertmate-26d10.firebaseapp.com',
    storageBucket: 'alertmate-26d10.firebasestorage.app',
    measurementId: 'G-667LR8YYNP',
    databaseURL: 'https://alertmate-26d10-default-rtdb.asia-southeast1.firebasedatabase.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZPuvo9VqO3588h-8NLEEV1w4CoOyYDhE',
    appId: '1:751235115727:android:673e833d82111d1ab6e5ba',
    messagingSenderId: '751235115727',
    projectId: 'alertmate-26d10',
    storageBucket: 'alertmate-26d10.firebasestorage.app',
    databaseURL: 'https://alertmate-26d10-default-rtdb.asia-southeast1.firebasedatabase.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1En4O-IWbztOda4bmutcHzloFQrmnitQ',
    appId: '1:751235115727:ios:9ae5369e7ed8b497b6e5ba',
    messagingSenderId: '751235115727',
    projectId: 'alertmate-26d10',
    storageBucket: 'alertmate-26d10.firebasestorage.app',
    iosBundleId: 'com.example.alertMate',
    databaseURL: 'https://alertmate-26d10-default-rtdb.asia-southeast1.firebasedatabase.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1En4O-IWbztOda4bmutcHzloFQrmnitQ',
    appId: '1:751235115727:ios:9ae5369e7ed8b497b6e5ba',
    messagingSenderId: '751235115727',
    projectId: 'alertmate-26d10',
    storageBucket: 'alertmate-26d10.firebasestorage.app',
    iosBundleId: 'com.example.alertMate',
    databaseURL: 'https://alertmate-26d10-default-rtdb.asia-southeast1.firebasedatabase.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCrRPgYs7mZ2piXxqSqkBf5XgXBnnja7RY',
    appId: '1:751235115727:web:340e1fc11acb85dcb6e5ba',
    messagingSenderId: '751235115727',
    projectId: 'alertmate-26d10',
    authDomain: 'alertmate-26d10.firebaseapp.com',
    storageBucket: 'alertmate-26d10.firebasestorage.app',
    measurementId: 'G-NLB4X5Q9RJ',
    databaseURL: 'https://alertmate-26d10-default-rtdb.asia-southeast1.firebasedatabase.app',
  );
}
